### ISSUE TITLE
Update DRF dependency

### ISSUE THREAD

**Issue by cfviotti** [labhackercd/audiencias-publicas#15]
Audiencias works well with DRF 3.6.2, but breaks on 3.7.1 :

```
ImportError: Could not import 'rest_framework.filters.DjangoFilterBackend' for API setting 'DEFAULT_FILTER_BACKENDS'. AttributeError: 'module' object has no attribute 'DjangoFilterBackend'.
```
